AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Unique Stable Matching Workflow

Globals:
  Function:
    Timeout: 30

Resources:
  SeedMarketGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: seed_market_generator/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SeedMarketQueue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref SeedMarketQueue

  SeedMarketQueue:
    Type: AWS::SQS::Queue

  DAResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "MarketId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "MarketId"
          KeyType: "HASH"

  SamplingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sampling_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DAResultsTable
      Events:
        SQSGetSeeds:
          Type: SQS
          Properties:
            Queue: !GetAtt SeedMarketQueue.Arn
            BatchSize: 3
            Enabled: true

      Environment:
        Variables:
          TABLE_NAME: !Ref DAResultsTable

Outputs:
  SeedMarketGeneratorFunctionOutput:
    Description: "Seed Market Generator Function ARN"
    Value: !GetAtt SeedMarketGeneratorFunction.Arn
  SeedMarketGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for Seed Market Generator Function"
    Value: !GetAtt SeedMarketGeneratorFunctionRole.Arn
  SeedMarketQueueOutput:
    Description: "Seed Market Queue ARN"
    Value: !GetAtt SeedMarketQueue.Arn
  SamplingFunctionOutput:
    Description: "Sampling Function ARN"
    Value: !GetAtt SamplingFunction.Arn
  SamplingFunctionIamRole:
    Description: "Implicit IAM Role created for Sampling Function"
    Value: !GetAtt SamplingFunctionRole.Arn
  DAResultsTableOutput:
    Description: "DynamoDB Table created to write DA results to"
    Value: !GetAtt DAResultsTable.Arn
