name: Unique Stable Matching Workflow
on:
  push:
    paths:
      - "seed_market_generator/**"
      - "template.yaml"
      - ".github/workflows/main.yml"
      - "tests/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run Python Tests
        # run: pip3 install pytest boto3 moto python-json-logger && python3 -m pytest tests/ -v
        run: echo "Run Python Tests"
      - name: Build Project
        run: sam build --use-container
      - name: Deploy Resources
        run: sam deploy --stack-name unique-stable-match --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --s3-bucket ${{ secrets.AWS_S3_SAM_BUCKET }} --no-fail-on-empty-changeset
